### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by danielgrijalva** [danielgrijalva/overworld#14] opened 2019-05-03 21:46 UTC
Must implement try/catch both in backend and frontend.

**Comment by danielgrijalva** [comment] 2019-06-03 19:48
Example 1: 
* Go to `Dragon Quest Builders 2`
* There's an error with the game's companies/developers

Example 2: 
* Go to `Doom: Eternal`
* The Release Date field says `Invalid date`

Example 3:
* Go to `Spitan Spirits Expedition - in the Phantasmagoria`
* Somethings wrong with the screenshots... `TypeError: Cannot read property '1' of undefined`

**Comment by raufabr** [comment] 2019-07-12 22:06
@danielgrijalva I am happy to pick this up. I tried searching the games but I couldn't load anything. Would like your help a bit in setting up my dev environment.

**Comment by danielgrijalva** [comment] 2019-07-13 00:04
@raufabr great, thanks! 😄

**Comment by raufabr** [comment] 2019-07-13 23:37
Hi, I need some help with this.

For Example 1, the website crashes when you click on Genres Tab with the following error: 

TypeError: Cannot read property 'map' of undefined in the following code in <Details /> component -

This bit of the code is throwing an error even though there is an array being passed.

I've tried a couple of different things but I couldn't figure out what the issue is.

**Option 1 - Make sure that game.genres isn't empty.**

```
{game.genres &&
                game.genres.map(g => {
                  return <Label key={g.index}>{g.name}</Label>;
})}
```

**Option 2 - Converted the object to Array and made sure we were passing in an array to map (not preferred)
**
```
//forcing the object to turn into an array
const changeToArray = obj => {
  return Object.keys(obj).map(k => obj[k]);
};

{game.genres &&
                changeToArray(game.genres).map(g => {
                  console.log(typeof game.genres && game);
                  return <Label key={g.index}>{g.name}</Label>;
 })}

```

Not sure if I'm just being silly here :

**Comment by danielgrijalva** [comment] 2019-07-14 04:47
@raufabr I noticed that bug too. The options you posted fix the issue? If so, option 1 seems more adequate 🤔

**Comment by raufabr** [comment] 2019-07-14 08:40
Neither options fix the issue and I'm lost :confused:

**Comment by raufabr** [comment] 2019-07-14 08:41
I'll work on the other 2 bugs now. I've just put an Error Boundary for the time being which won't at least crash the website.

**Comment by danielgrijalva** [comment] 2019-07-14 23:17
@raufabr I just noticed something: it's not the `genres` that are causing the problem, is the `themes` array!

```js
{game.themes.map(t => {
  return <Label key={t.id}>{t.name}</Label>;
})}
```

The game DQ Builders 2 doesn't have any `themes`, that's why it's `undefined`. The solution would be to apply option 1 (check if games.themes exists).

```js
{games.themes && game.themes.map(t => {
  return <Label key={t.id}>{t.name}</Label>;
})}
```

**Comment by raufabr** [comment] 2019-07-15 22:46
OK that is really weird! Because the browser throws a different error. I'll commit my changes and update my PR tomorrow. Sorry for the delay, I've been working all day today. :tired_face:

**Comment by danielgrijalva** [comment] 2019-07-16 00:42
@raufabr no worries man! 😄

**Comment by raufabr** [comment] 2019-07-16 22:08
Thanks @danielgrijalva 
I dunno what happened but I kept looking at genres and not themes. :disappointed:
One of those bugs.

**Comment by raufabr** [comment] 2019-07-16 22:09
I've updated my latest code in the pull request. Will fix example 3 and submit my fix by tomorrow morning.

**Comment by raufabr** [comment] 2019-07-17 19:34
This should be fixed now. Let me know if anything else is required. 
:smile:

**Closed** 2019-07-19 18:42 UTC
Labels: good first issue :egg:, up for grabs :zap:
